export enum EPaymentStatus {
  FAILED = 'FAILED',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  UNPAID = 'UNPAID',
}

export enum EOrderStatus {
  UNPAID = 'UNPAID',
  PENDING = 'PENDING',
  PREPARED = 'PREPARED',
  SHIPPING = 'SHIPPING',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
